#!/bin/sh

sudo apt install \
     aptitude \
     arandr \
     build-essential \
     compton \
     curl \
     emacs25 \
     etckeeper \
     feh \
     fbreader \
     git \
     gksu \
     gnupg2 \
     graphviz \
     htop \
     i3 \
     imagemagick \
     isync \
     libnotify-bin \
     maildir-utils \
     make \
     mpd \
     mpv \
     msmtp \
     openssl \
     pandoc \
     pass \
     pasystray \
     procmail \
     pwgen \
     python3 \
     python3-pip \
     redshift \
     rlwrap \
     rofi \
     rxvt-unicode \
     scrot \
     silversearcher-ag \
     stow \
     sudo \
     texlive-base \
     texlive-fonts-recommended \
     texlive-latex-base \
     tree \
     unclutter \
     unifont \
     unrar \
     urlscan \
     urlview \
     vim \
     w3m \
     xbindkeys \
     xcape \
     xdotool \
     xsel \
     zathura
