#!/bin/sh

sudo apt install \
     aptitude \
     arandr \
     bash-completion \
     build-essential \
     calibre \
     curl \
     dvipng \
     emacs \
     etckeeper \
     fbreader \
     fd-find \
     feh \
     fuse \
     gawk \
     git \
     gnumeric \
     gnupg2 \
     graphviz \
     htop \
     i3 \
     i3lock \
     imagemagick \
     isync \
     jq \
     libnotify-bin \
     libpq-dev \
     libsqlite3-dev \
     lightdm \
     kitty \
     maildir-utils \
     make \
     mlocate \
     mpv \
     msmtp \
     npm \
     opam \
     openssl \
     pandoc \
     parallel \
     pass \
     pass-extension-otp \
     pasystray \
     pavucontrol \
     pcmanfm \
     picom \
     polybar \
     postgresql \
     procmail \
     pwgen \
     python3 \
     python3-gpg \
     python3-pip \
     redshift \
     restic \
     ripgrep \
     rlwrap \
     rofi \
     rsync \
     scrot \
     shellcheck \
     sqlite3 \
     sqlite3-pcre \
     stow \
     sudo \
     texlive-base \
     texlive-fonts-recommended \
     texlive-latex-base \
     tree \
     unclutter \
     unifont \
     unrar \
     urlscan \
     urlview \
     vim \
     w3m \
     wget \
     xbindkeys \
     xcape \
     xdotool \
     xfce4-clipman \
     xsel \
     zathura \
     zathura-cb
