#!/usr/bin/env ruby

require "json"
require "fuzz"

SCREEN_LAYOUT_DEFINITIONS = File.expand_path(
  "~/.screen-layouts.json",
)

class MonitorConfiguration
  def initialize(command:, name:)
    @command = command
    @name = name
  end

  def to_s
    name
  end

  def exec
    system(command)
  end

  def self.from_json(json)
    new(
      name: json.fetch("name"),
      command: json.fetch("command"),
    )
  end

  private

  attr_reader :command, :name
end

json = JSON.parse(File.read(SCREEN_LAYOUT_DEFINITIONS))
configurations = json.map { |config|
  MonitorConfiguration.from_json(config)
}

chosen_configuration = if ARGV.empty?
  Fuzz::Selector.new(
    configurations,
    cache: Fuzz::Cache.new("~/.cache/fuzz/change_monitor"),
  ).pick
else
  configurations[ARGV[0].to_i]
end

chosen_configuration.exec

system(File.expand_path("~/.bin/set-wallpaper"))
