#!/bin/bash

# Add a URL to Instapaper.
#
# Usage:
#
# $ instapaper <url> <optional-article-title>

username=$(netrc login "instapaper.com")
password=$(netrc password "instapaper.com")

ricepaper -u $username -p $password "$1" > /dev/null &
