#!/bin/sh

# Pause VLC if it's running.
dbus-send --type=method_call \
          --dest=org.mpris.MediaPlayer2.vlc \
          /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause

# Pause music if it's playing.
mpc pause
quodlibet --pause

# Disable dunst notifications.
pkill -u "$USER" -USR1 dunst

# Lock the screen with a simple tiling background. The `--nofork` option blocks,
# ensuring that dunst messages aren't re-enabled immediately.
i3lock --nofork \
       --tiling \
       --image=/home/hrs/pictures/wallpaper/tile/background-tile.png

# Re-enable dunst notifications.
pkill -u "$USER" -USR2 dunst
