#!/usr/bin/python
import sys, re

if len(sys.argv) != 2:
  print "Usage:", sys.argv[0], "<input_file>"
  sys.exit()

FILE = sys.argv[1]
new_data = (re.sub('\015', '' , line) for line in open(FILE, 'r').readlines())

new_file = open("%s.new" % FILE, 'w')

for line in new_data:
  print line
  new_file.write(line)

new_file.close()

print "Converted text saved as %s.new" % FILE
