#!/bin/bash

bookmarks="$HOME/documents/org/links.org"

if [ $# -eq 0 ]; then
   echo "Usage: bookmark URL [title]"
   exit 1
fi

url="$1"
shift
title="$*"

if [[ "$title" == "" ]]; then
  if grep "\\** \[\[$url\]\]" "$bookmarks"; then
    notify-send "Already bookmarked!"
    exit 1
  else
    echo "** [[$url]]" >> "$bookmarks"
    notify-send "Bookmarked!"
  fi
else
  if grep "\\** \[\[$url\]\[$title\]\]" "$bookmarks"; then
    notify-send "Already bookmarked!"
    exit 1
  else
    echo "** [[$url][$title]]" >> "$bookmarks"
    notify-send "Bookmarked!"
  fi
fi
