#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

# Kill any running processes
if pgrep --exact mbsync; then
  pkill --exact mbsync
fi
if pgrep --exact mu; then
  pkill --exact mu
fi

# Fetch new mail
mbsync personal

# Index new mail
mu index --nocolor
