#!/usr/bin/env bash

netrc="$HOME/.netrc"

if [ ! $# -eq 2 ]; then
  echo "Usage: $0 (login | password) [machine]"
  exit 1
fi

field="$1"
machine="$2"

if [ "$field" == "login" ]; then
  cat "$netrc" | grep "$machine" | head -1 | cut -d" " -f4
elif [ "$field" == "password" ]; then
  cat "$netrc" | grep "$machine" | head -1 | cut -d" " -f6
else
  echo "Usage: $0 (login | password) [machine]"
  exit 1
fi
