#!/bin/bash

set -e

# Remove non-canonical repos. I only use a single /etc/apt/sources.list.
sudo rm -rf /etc/apt/sources.list.d

# Refresh package lists from all repositories.
sudo apt update

# Upgrade the whole system, possibly removing packages if needed.
sudo apt full-upgrade

# Remove any dependencies that are no longer necessary.
sudo apt autoremove

# Tidy up the package cache, deleting any package files that no longer exist in
# our repository sources.
sudo aptitude autoclean
