#!/usr/bin/env ruby

require "fuzz"

TOKENS_DIRECTORY = File.expand_path("~/.password-store/tokens")

class Token
  def initialize(gpg_file_path)
    @path = gpg_file_path
  end

  def to_s
    path.split("/").last.sub(".gpg", "")
  end

  def totp_code
    `~/.bin/2fa #{ to_s }`.strip
  end

  private

  attr_reader :path
end

def tokens
  Dir.glob("#{ TOKENS_DIRECTORY }/*").map { |path| Token.new(path) }
end

def pick_token
  Fuzz::Selector.new(tokens).pick
end

`xdotool type #{ pick_token.totp_code }`
