#!/bin/sh
# Remove the trailing whitespaces from the files to be committed.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
  # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for f in `exec git diff-index --cached --check $against -- | sed '/^[-+]/d' | cut -d: -f1 | uniq` ; do
    echo "* Removed whitespace: $f"
    if [[ $(uname) == Darwin ]]; then
        sed -i '' -E 's/[[:space:]]*$//' $f
    else
        sed -i 's/[[:space:]]*$//' $f
    fi
    git add $f
done
